src/freelance/freelance/urls.py
from django.contrib import admin
from accounts.views import register_acc, login, logout
from django.urls import path, include, re_path
from task.views import *

def base_view(request):
    return render(request, 'not_found.html')

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', register_acc, name= 'register'),
    path('login/', login, name= 'login'),
    path('logout/', logout, name= 'logout'),
    path('home/', include('task.urls')),
    re_path(r'^', base_view, name='back_home')
]

src/freelance/task/urls.py
from django.urls import path
from task.views import *

app_name = 'task'


#this is /home/
urlpatterns = [
    path('', home_view, name='home'),
    path('add-problem/', add_problem, name= 'add-problem'),
    path('myapplications/', application_view, name= 'myapplications'),
    path('problems/', problem_view, name= 'problems'),
    path('problem/<int:id>/', problem_view_single, name= 'problem'),
    path('<str:user>', user_view, name = 'user')
]

src/freelance/accounts/models.py
from django.db import models

# Create your models here.

src/freelance/task/models.py
from django.db import models
from django.db.models.deletion import CASCADE

# Create your models here.


class Language(models.Model):
    def __str__(self) -> str:
        return self.name
    name = models.CharField(max_length=20,unique=True, null=False)
    

class Problem(models.Model):
    def __str__(self) -> str:
        return "<h3>Title:" + self.title + "</h3><h4>Description " + self.description + "</h4>" + "<h4>Posted by " + self.user_name + "</h4>" 
    title = models.CharField(max_length=30, null=False)
    description = models.CharField(max_length=300, null=False)
    user_name = models.CharField(max_length=30, null=False, default="")
    language = models.ForeignKey(Language, on_delete=CASCADE)
    hidden = models.BooleanField(default=False)
    available = models.BooleanField(default=True)

class Application(models.Model):
    problem = models.ForeignKey(Problem, on_delete=CASCADE)
    user_name = models.CharField(max_length=30, null=False,default="")
    accepted = models.BooleanField(default = False)

    

src/freelance/accounts/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm, fields
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']

src/freelance/task/forms.py
from django import forms
from django.db import models
from django.forms import ModelForm, fields
from .models import Problem, Language
from django import forms

class CreateProblemForm(forms.ModelForm):

    class Meta:
        model = Problem
        fields = ['title', 'description', 'language']
        

src/freelance/accounts/views.py
from django import forms
from django.shortcuts import render, redirect
from django.http import HttpResponse  
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib import messages

from .forms import CreateUserForm

# Create your views here.

def register_acc(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid:
            form.save()
            return redirect('login')
            
    
    context = {'form' : form}
    return render(request, 'register.html', context)

def login(request):
    
    if request.user.is_authenticated:
        return redirect('task:home')

    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            auth_login(request, user)
            return redirect('task:home')
        else:
            messages.info(request, 'User or password is incorrect')
    
    context = {}
    
    return render(request, 'login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('login')

src/freelance/task/views.py
from django.core.files.base import ContentFile
from django.core.paginator import EmptyPage, Paginator
from django.db.models import query
from django.utils import tree
from task.models import *
from django.http import HttpResponse
from django.shortcuts import render, redirect
from task.models import *
from django.contrib import messages
from .forms import CreateProblemForm
from django.db.models import Q
from django.contrib.auth.models import User




# Create your views here.
def home_view(request, *args, **kwargs):
    if(request.user.is_authenticated):
        if request.method == 'POST':
            user = request.user.username
            problem = request.POST.get('problem')

            cnt = Application.objects.all().filter(problem_id__exact= problem).filter(user_name__exact = user).count()
            
            if cnt == 0:
                Application.objects.create(problem_id=problem, user_name = user)
                messages.warning(request, 'You successfully applied')
            else:
                messages.warning(request, 'You already applied')
            return redirect('/home/')
        problems = Problem.objects.all().filter(hidden=False)
        p = Paginator(problems, 6)

        page_num = request.GET.get('page', 1)

        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        
        return render(request, "home.html", {'problems': page})
    return redirect('login')
    

def add_problem(request):
    if(request.user.is_authenticated):
        form = CreateProblemForm()
        user = request.user.username

        if request.method == 'POST':
            form = CreateProblemForm(request.POST or None)
            if form.is_valid():
                form.cleaned_data['user'] = user
                problem = Problem(title = form.cleaned_data['title'], description = form.cleaned_data['description'],
                                    language = form.cleaned_data['language'], user_name = form.cleaned_data['user'])
                problem.save()
                return redirect('/home/')
    
        context = {'form' : form}
        return render(request, 'add-problem.html', context)
    return redirect('login')


def application_view(request):
    if(request.user.is_authenticated):
        user = request.user.username
        query = Application.objects.all().filter(user_name__exact= user)
        p = Paginator(query, 6)

        page_num = request.GET.get('page', 1)

        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context = {
            'my_apps': page
        }
        return render(request, 'my_application.html', context)
    return redirect('login')


def problem_view(request):
    if(request.user.is_authenticated):
        user = request.user.username
        query = Problem.objects.all().filter(user_name__exact= user, hidden=False)
        p = Paginator(query, 6)

        page_num = request.GET.get('page', 1)

        try:
            page = p.page(page_num)
        except EmptyPage:
            page = p.page(1)
        context = {
            'problems': page
        }
        return render(request, 'problems.html', context)
    return redirect('login')

def problem_view_single(request, id):
    if(request.user.is_authenticated):

        if request.method == 'POST':
            appid = request.POST.get('appid')
            probid = request.POST.get('probid')

            Application.objects.all().filter(id=appid).update(accepted=True)
            Problem.objects.all().filter(id=probid).update(hidden=True, available=False)
            return redirect('/home/')

        user = request.user.username
        problem = Problem.objects.all().filter(id__exact = id)
        
        application = Application.objects.all().filter(problem_id__exact=id)
        context = {
            'problem': problem.first(),
            'applications': application
        }

        return render(request, 'applications.html', context)
    return redirect('login')

def user_view(request, user):
    query = Application.objects.all().filter(user_name__exact = user)
    nr_entries = query.count()
    nr_accepted = query.filter(accepted__exact=True).count()

    email = User.objects.all().filter(username=user).first().email

    context = {
        'nr_entries': nr_entries,
        'nr_accepted': nr_accepted,
        'user_name': user,
        'email': email
    }

    return render(request, 'user.html', context)

src/freelance/templates/add-problem.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">




{% extends "base.html" %}


{% block content %}

{% include 'navbar.html' %}

    <br>
    <div class="container">
        <div class="row">
            <div class="d-flex justify-content-center col-12">
                <form method="post" class="w-75">
                    {% csrf_token %}
                    <div class="form-group>
                        <label for="exampleFormControlInput1">Title</label>
                        <input type="text" class="form-control" id="id_title" name="title" placeholder="Problem title" maxlength="30" required="">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlInput1">Description</label>
                        <input type="text" class="form-control" id="id_description" name="description" placeholder="Description" maxlength="300" required="">
                    </div>
                    <div class="form-group">
                        <label for="exampleFormControlSelect1">Language</label>
                        <select class="form-control" name="language" id="id_language" required="">
                            {% for x,y in form.fields.language.choices %}
                                <option value="{{x}}">{{y}}</option>
                            {%endfor%}
                        </select>
                    </div>
                    <button type="submit" class="btn btn-primary">Add new problem</button>
                </form>
            </div>
        </div>
    </div>

{% endblock content %}

src/freelance/templates/applications.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">


{% extends "base.html" %}




{% block content %}

{% include 'navbar.html' %}

<div class="container">
    <div class="row">

        <div style="margin-bottom: 20px;" class="col-12">
            <div class="card w-100">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ problem.title }}</h5>
                    <h6 class="card-subtitle mb-2 text-muted text-center">Language: {{ problem.language.name }}</h6>
                    <br>
                    <h6 class="card-subtitle mb-2 text-center">Description:</h6>
                    <p class="card-text text-center">{{ problem.description }}</p>
                </div>
            </div>
        </div>
    </div>
</div>






<div class="container">
    <div class="row">
        {% for app in applications %}
            <div style="margin-bottom: 20px;" class="col-6">
                <div class="card w-100">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ app.user_name }}</h5>
                        <br>
                        <p class="card-subtitle mb-2 text-center">
                            <a href="{% url 'task:user' app.user_name %}" class="card-subtitle mb-2 text-center">
                            Details here
                            </a>
                        </p> 
                        <form method="post" action="">
                            {% csrf_token %}
                            <form method="POST" action="">
                                {% csrf_token %}
                                <input type="hidden" name= 'appid' value= '{{app.id}}'>
                                <input type="hidden" name= 'probid' value= '{{problem.id}}'>
                                <input type="hidden" name= 'user' value= '{{app.user_name}}'>
                                <button type="submit" class="btn btn-primary col-12">Accept</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>


{% endblock content %}

src/freelance/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        {% block head %}{% endblock head %}
    </head>

    <body>
        {% block content %}{% endblock content %}
    </body>
</html>

src/freelance/templates/home.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">

{% extends "base.html" %}

{% block content %}

{% include 'navbar.html' %}

<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
          {% if problems.has_previous %}
        <a class="page-link" href="{% url 'task:home' %}?page={{problems.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
          {% endif %}
      </li>
      {% for i in problems.paginator.page_range %}
      {% ifequal i problems.number %}
        <li class="page-item active">
            <a class="page-link" href="{% url 'task:home' %}?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{% url 'task:home' %}?page={{forloop.counter}}">{{forloop.counter}}</a></li>
        {% endifequal %}
      {%endfor%}
      <li class="page-item">
        {% if problems.has_next %}
        <a class="page-link" href="{% url 'task:home' %}?page={{problems.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </nav>


<h4 class="messages">
    {% for message in messages %}
    <li {% if message.tags %} class=" {{ message.tags }} " {% endif %}> {{ message }} </li>
    {% endfor %}
</h4>


<div class="container">
    <div class="row">
        {% for problem in problems %}
            <div style="margin-bottom: 20px;" class="col-6">
                <div class="card w-100">
                    <div class="card-body">
                        <h5 class="card-title text-center">{{ problem.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted text-center">Language: {{ problem.language.name }}</h6>
                        <br>
                        <h6 class="card-subtitle mb-2 text-center">Description:</h6>
                        <p class="card-text text-center">{{ problem.description }}</p>
                        <form method="post" action="">
                            {% csrf_token %}
                            <input type="hidden" name="problem" value="{{problem.id}}">
                            <button type="submit" class="btn btn-primary col-12">Apply</button>
                        </form>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
</div>




{% endblock content %}

src/freelance/templates/login.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Login</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="password" name="password" id="password" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="Login">
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'register' %}"class="text-info">Register here</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

src/freelance/templates/my_application.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">


{% extends "base.html" %}


{% block content %}

{% include 'navbar.html' %}


<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
          {% if my_apps.has_previous %}
        <a class="page-link" href="{% url 'task:myapplications' %}?page={{my_apps.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
          {% endif %}
      </li>
      {% for i in my_apps.paginator.page_range %}
      {% ifequal i my_apps.number %}
        <li class="page-item active">
            <a class="page-link" href="{% url 'task:myapplications' %}?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{% url 'task:myapplications' %}?page={{forloop.counter}}">{{forloop.counter}}</a></li>
        {% endifequal %}
      {%endfor%}
      <li class="page-item">
        {% if my_apps.has_next %}
        <a class="page-link" href="{% url 'task:myapplications' %}?page={{my_apps.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </nav>

<div class="container">
   <div class="row">
       {% for app in my_apps %}
           <div style="margin-bottom: 20px;" class="col-6">
               <div class="card w-100{%if app.problem.available%} bg-light mb-3{%elif app.accepted%} bg-success mb-3{%else%} bg-danger mb-3{%endif%}">
                   <div class="card-body">
                       <h5 class="card-title text-center">{{ app.user_name }}</h5>
                       <br>
                       <h5 class="card-title text-center">{{ app.problem.title }}</h5>
                        <h6 class="card-subtitle mb-2 text-muted text-center">Language: {{ app.problem.language.name }}</h6>
                       <p class="card-subtitle mb-2 text-center">Accepted: {{app.accepted}}</p>

                   </div>
               </div>
           </div>
       {% endfor %}
   </div>
</div>

{% endblock content %}

src/freelance/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
      <a class="navbar-brand">Hi, {{user.get_username}}</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'task:home'%}">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'task:add-problem'%}">Add problem</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'task:problems'%}">Your problems</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'task:myapplications' %}">Your Applications</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="{% url 'logout' %}">Logout</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>

src/freelance/templates/not_found.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->
<br>
<br>
<br>
<br>
<br>
<br>
<div class="page-wrap d-flex flex-row align-items-center">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 text-center">
                <span class="display-1 d-block">404</span>
                <div class="mb-4 lead">The page you are looking for was not found.</div>
                <a href="{% url 'task:home'%}" class="btn btn-link">Back to Home</a>
            </div>
        </div>
    </div>
</div>

src/freelance/templates/problems.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">

{% extends "base.html" %}

{% block content %}

{% include 'navbar.html' %}

<nav aria-label="Page navigation example">
    <ul class="pagination">
      <li class="page-item">
          {% if problems.has_previous %}
        <a class="page-link" href="{% url 'task:problems' %}?page={{problems.previous_page_number}}" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
          {% endif %}
      </li>
      {% for i in problems.paginator.page_range %}
      {% ifequal i problems.number %}
        <li class="page-item active">
            <a class="page-link" href="{% url 'task:problems' %}?page={{forloop.counter}}">{{forloop.counter}}<span class="sr-only">(current)</span></a>
        </li>
        {% else %}
        <li class="page-item"><a class="page-link" href="{% url 'task:problems' %}?page={{forloop.counter}}">{{forloop.counter}}</a></li>
        {% endifequal %}
      {%endfor%}
      <li class="page-item">
        {% if problems.has_next %}
        <a class="page-link" href="{% url 'task:problems' %}?page={{problems.next_page_number}}" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
        {% endif %}
      </li>
    </ul>
  </nav>


<div class="container">
    <div class="row">
        {% for problem in problems %}
            {% if not problem.hidden %}
                <div style="margin-bottom: 20px;" class="col-6">
                    <div class="card w-100">
                        <div class="card-body">
                            <h5 class="card-title text-center">{{ problem.title }}</h5>
                            <h6 class="card-subtitle mb-2 text-muted text-center">Language: {{ problem.language.name }}</h6>
                            <br>
                            <h6 class="card-subtitle mb-2 text-center">Description:</h6>
                            <p class="card-text text-center">{{ problem.description }}</p>
                            <a href="{% url 'task:problem' problem.id %}" class="btn btn-primary col-12">Go to applications</a>

                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>
</div>


{% endblock content %}

src/freelance/templates/register.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<!------ Include the above in your HEAD tag ---------->

<body>
    <div id="login">
        <h3 class="text-center text-white pt-5">Login form</h3>
        <div class="container">
            <div id="login-row" class="row justify-content-center align-items-center">
                <div id="login-column" class="col-md-6">
                    <div id="login-box" class="col-md-12">
                        <form id="login-form" class="form" action="" method="post">
                            {% csrf_token %}
                            <h3 class="text-center text-info">Register</h3>
                            <div class="form-group">
                                <label for="username" class="text-info">Username:</label><br>
                                <input type="text" name="username" id="username" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="email" class="text-info">Email:</label><br>
                                <input type="email" name="email" maxlength="254" id="id_email" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Password:</label><br>
                                <input type="password" name="password1" autocomplete="new-password" required="" id="id_password1" class="form-control">
                            </div>
                            <div class="form-group">
                                <label for="password" class="text-info">Confirm password:</label><br>
                                <input type="password" name="password2" autocomplete="new-password" required="" id="id_password2" class="form-control">
                            </div>
                            <div class="form-group">
                                <input type="submit" name="submit" class="btn btn-info btn-md" value="Register">
                            </div>
                            <div id="register-link" class="text-right">
                                <a href="{% url 'login' %}" class="text-info" >Login</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>

src/freelance/templates/user.html
<link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.css" rel="stylesheet" id="bootstrap-css">

{% extends "base.html" %}

{% block content %}

{% include 'navbar.html' %}


<div class="container">
    <div class="row">
        <div style="margin-bottom: 20px;" class="col-12">
            <div class="card w-100">
                <div class="card-body">
                    <h5 class="card-title text-center">{{ user_name }}</h5>
                    <h5 class="card-title text-center">Contact: {{ email }}</h5>
                    <br>
                    <p class="card-subtitle mb-2 text-center">Experience on our site:</p>
                    <h6 class="card-text text-center">{{user_name}} has applied for {{nr_entries}} problems</h6>
                    <h6 class="card-text text-center">{{nr_accepted}} were successful</h6>
                </div>
            </div>
        </div>
    </div>
</div>



{% endblock content %}